name: Create PR for Deploy

on:
  repository_dispatch:
    types: [create-pr-for-deploy]
        

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit sha
        id: commit-sha
        run: |
          sha=${{ github.event.client_payload.sha }}
          echo ${sha}
          sha_short=${sha:0:7}
          echo "Short commit sha: ${sha_short}"
          echo "sha_short=$sha_short" >> "$GITHUB_OUTPUT"

      - name: Create branch
        id: create-branch
        run: |
          branch_name='deploy/${{ github.event.client_payload.service }}-${{ github.event.client_payload.env }}-${{steps.commit-sha.outputs.sha_short}}'
          git checkout -b ${branch_name}
          echo "branch_name=$branch_name" >> "$GITHUB_OUTPUT"
      - name: modify file
        run: |
          echo "Nueva línea añadida" >> output.txt

      - name: Setup Git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'jabl01'
          git config --global user.email 'jabl01@betssongroup.com'
          git remote set-url origin https://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@github.com/jabl01/dummy-repo-simulate-argocd.git
          git ls-remote origin

      - name: Commit and Push Changes
        run: |
          git add --all
          git commit -m "Update docker image tag for on environment" || echo "No changes to commit"
          git push origin HEAD:refs/heads/deploy/--

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr create --title 'Deploy   to  environment' \
                       --body 'Deployment triggered by ' \
                       --head deploy/--

      - name: Approve Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          pr_url=$(gh pr view --json url -q '.url')
          gh pr review $pr_url --approve